apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-analytic-service
  labels:
    app: skill-analytic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill-analytic-service
  template:
    metadata:
      labels:
        app: skill-analytic-service
    spec:
      containers:
      - name: skill-analytic-service
        image: devlifestartup/ENV_JOB_BASE_NAME:ENV_VERSION.ENV_BUILD_NUMBER
        ports:
        - containerPort: 8088
        env:
          - name: DATASOURCE_HOST
            value: ENV_DATASOURCE_HOST
          - name: DATASOURCE_PORT
            value: ENV_DATASOURCE_PORT
          - name: SERVICE_NAME
            value: ENV_SERVICE_NAME
          - name: SERVICE_PORT
            value: ENV_SERVICE_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: skill-analytic-service
spec:
  selector:
    app: skill-analytic-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088