apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-analytic-service
  labels:
    app: skill-analytic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill-analytic-service
  template:
    metadata:
      labels:
        app: skill-analytic-service
    spec:
      containers:
      - name: skill-analytic-service
        image: devlifestartup/skill_analytic_service:1.0.0
        ports:
        - containerPort: 8088
        env:
        - name: DATASOURCE_HOST
          value: db.bromen.fun
        - name: DATASOURCE_PORT
          value: "5432"
        - name: SERVICE_NAME
          value: skills
        - name: SERVICE_PORT
          value: "8088"

---
apiVersion: v1
kind: Service
metadata:
  name: skill-analytic-service
spec:
  selector:
    #app.kubernetes.io/name: cats-api
    app: skill-analytic-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088